import bpy

# ===============================
# Bone name replacements mapping
# ===============================
bone_replacements = {
    # Core
    "Hips"                  : "ValveBiped.Bip01_Pelvis",
    "Spine"                 : "ValveBiped.Bip01_Spine",
    "Chest"                 : "ValveBiped.Bip01_Spine4",
    "Neck"                  : "ValveBiped.Bip01_Neck1",
    "Head"                  : "ValveBiped.Bip01_Head1",

    # ---- LEFT ARM ----
    "Shoulder_L"            : "ValveBiped.Bip01_L_Clavicle",
    "Shoulder_l"            : "ValveBiped.Bip01_L_Clavicle",
    "Shoulder.L"            : "ValveBiped.Bip01_L_Clavicle",
    "Shoulder.l"            : "ValveBiped.Bip01_L_Clavicle",
    "Left_shoulder"         : "ValveBiped.Bip01_L_Clavicle",
    "Left shoulder"         : "ValveBiped.Bip01_L_Clavicle",
    "Left_Shoulder"         : "ValveBiped.Bip01_L_Clavicle",
    "Left Shoulder"         : "ValveBiped.Bip01_L_Clavicle",
    "left_shoulder"         : "ValveBiped.Bip01_L_Clavicle",
    "left shoulder"         : "ValveBiped.Bip01_L_Clavicle",
    "LeftShoulder"          : "ValveBiped.Bip01_L_Clavicle",

    "UpperArm_L"            : "ValveBiped.Bip01_L_UpperArm",
    "UpperArm_l"            : "ValveBiped.Bip01_L_UpperArm",
    "Upper_arm.L"           : "ValveBiped.Bip01_L_UpperArm",
    "Upper_arm.l"           : "ValveBiped.Bip01_L_UpperArm",
    "Left_arm"              : "ValveBiped.Bip01_L_UpperArm",
    "Left arm"              : "ValveBiped.Bip01_L_UpperArm",
    "Left_Arm"              : "ValveBiped.Bip01_L_UpperArm",
    "Left Arm"              : "ValveBiped.Bip01_L_UpperArm",
    "LeftUpperArm"          : "ValveBiped.Bip01_L_UpperArm",

    "LowerArm_L"            : "ValveBiped.Bip01_L_Forearm",
    "Lower_arm.L"           : "ValveBiped.Bip01_L_Forearm",
    "LowerArm_l"            : "ValveBiped.Bip01_L_Forearm",
    "Lower_arm.l"           : "ValveBiped.Bip01_L_Forearm",
    "Left_elbow"            : "ValveBiped.Bip01_L_Forearm",
    "Left elbow"            : "ValveBiped.Bip01_L_Forearm",
    "Left_Elbow"            : "ValveBiped.Bip01_L_Forearm",
    "Left Elbow"            : "ValveBiped.Bip01_L_Forearm",
    "LeftLowerArm"          : "ValveBiped.Bip01_L_Forearm",

    "Hand_L"                : "ValveBiped.Bip01_L_Hand",
    "Hand.L"                : "ValveBiped.Bip01_L_Hand",
    "Hand_l"                : "ValveBiped.Bip01_L_Hand",
    "Hand.l"                : "ValveBiped.Bip01_L_Hand",
    "Left_wrist"            : "ValveBiped.Bip01_L_Hand",
    "Left wrist"            : "ValveBiped.Bip01_L_Hand",
    "Left_Wrist"            : "ValveBiped.Bip01_L_Hand",
    "Left Wrist"            : "ValveBiped.Bip01_L_Hand",
    "LeftHand"              : "ValveBiped.Bip01_L_Hand", 

    # Fingers (Left) I
    "ThumbProximal_L"       : "ValveBiped.Bip01_L_Finger0",
    "ThumbIntermediate_L"   : "ValveBiped.Bip01_L_Finger01",
    "ThumbDistal_L"         : "ValveBiped.Bip01_L_Finger02",
    "IndexProximal_L"       : "ValveBiped.Bip01_L_Finger1",
    "IndexIntermediate_L"   : "ValveBiped.Bip01_L_Finger11",
    "IndexDistal_L"         : "ValveBiped.Bip01_L_Finger12",
    "MiddleProximal_L"      : "ValveBiped.Bip01_L_Finger2",
    "MiddleIntermediate_L"  : "ValveBiped.Bip01_L_Finger21",
    "MiddleDistal_L"        : "ValveBiped.Bip01_L_Finger22",
    "RingProximal_L"        : "ValveBiped.Bip01_L_Finger3",
    "RingIntermediate_L"    : "ValveBiped.Bip01_L_Finger31",
    "RingDistal_L"          : "ValveBiped.Bip01_L_Finger32",
    "LittleProximal_L"      : "ValveBiped.Bip01_L_Finger4",
    "LittleIntermediate_L"  : "ValveBiped.Bip01_L_Finger41",
    "LittleDistal_L"        : "ValveBiped.Bip01_L_Finger42",
    
    # Fingers (Left) II
    "Thumb01_l"             : "ValveBiped.Bip01_L_Finger0",
    "Thumb02_l"             : "ValveBiped.Bip01_L_Finger01",
    "Thumb03_l"             : "ValveBiped.Bip01_L_Finger02",
    "Index01_l"             : "ValveBiped.Bip01_L_Finger1",
    "Index02_l"             : "ValveBiped.Bip01_L_Finger11",
    "Index03_l"             : "ValveBiped.Bip01_L_Finger12",
    "Middle01_l"            : "ValveBiped.Bip01_L_Finger2",
    "Middle02_l"            : "ValveBiped.Bip01_L_Finger21",
    "Middle03_l"            : "ValveBiped.Bip01_L_Finger22",
    "Ring01_l"              : "ValveBiped.Bip01_L_Finger3",
    "Ring02_l"              : "ValveBiped.Bip01_L_Finger31",
    "Ring03_l"              : "ValveBiped.Bip01_L_Finger32",
    "Little01_l"            : "ValveBiped.Bip01_L_Finger4",
    "Little02_l"            : "ValveBiped.Bip01_L_Finger41",
    "Little03_l"            : "ValveBiped.Bip01_L_Finger42",
    
    # Fingers (Left) III
    "Thumb Proximal_L"      : "ValveBiped.Bip01_L_Finger0",
    "Thumb Intermediate_L"  : "ValveBiped.Bip01_L_Finger01",
    "Thumb Distal_L"        : "ValveBiped.Bip01_L_Finger02",
    "Index Proximal_L"      : "ValveBiped.Bip01_L_Finger1",
    "Index Intermediate_L"  : "ValveBiped.Bip01_L_Finger11",
    "Index Distal_L"        : "ValveBiped.Bip01_L_Finger12",
    "Middle Proximal_L"     : "ValveBiped.Bip01_L_Finger2",
    "Middle Intermediate_L" : "ValveBiped.Bip01_L_Finger21",
    "Middle Distal_L"       : "ValveBiped.Bip01_L_Finger22",
    "Ring Proximal_L"       : "ValveBiped.Bip01_L_Finger3",
    "Ring Intermediate_L"   : "ValveBiped.Bip01_L_Finger31",
    "Ring Distal_L"         : "ValveBiped.Bip01_L_Finger32",
    "Little Proximal_L"     : "ValveBiped.Bip01_L_Finger4",
    "Little Intermediate_L" : "ValveBiped.Bip01_L_Finger41",
    "Little Distal_L"       : "ValveBiped.Bip01_L_Finger42",
    
    # Fingers (Left) IV
    "Thumb Proximal.L"      : "ValveBiped.Bip01_L_Finger0",
    "Thumb Intermediate.L"  : "ValveBiped.Bip01_L_Finger01",
    "Thumb Distal.L"        : "ValveBiped.Bip01_L_Finger02",
    "Index Proximal.L"      : "ValveBiped.Bip01_L_Finger1",
    "Index Intermediate.L"  : "ValveBiped.Bip01_L_Finger11",
    "Index Distal.L"        : "ValveBiped.Bip01_L_Finger12",
    "Middle Proximal.L"     : "ValveBiped.Bip01_L_Finger2",
    "Middle Intermediate.L" : "ValveBiped.Bip01_L_Finger21",
    "Middle Distal.L"       : "ValveBiped.Bip01_L_Finger22",
    "Ring Proximal.L"       : "ValveBiped.Bip01_L_Finger3",
    "Ring Intermediate.L"   : "ValveBiped.Bip01_L_Finger31",
    "Ring Distal.L"         : "ValveBiped.Bip01_L_Finger32",
    "Little Proximal.L"     : "ValveBiped.Bip01_L_Finger4",
    "Little Intermediate.L" : "ValveBiped.Bip01_L_Finger41",
    "Little Distal.L"       : "ValveBiped.Bip01_L_Finger42",
    
    # Fingers (Left) V
    "Thumb_Proximal_L"      : "ValveBiped.Bip01_L_Finger0",
    "Thumb_Intermediate_L"  : "ValveBiped.Bip01_L_Finger01",
    "Thumb_Distal_L"        : "ValveBiped.Bip01_L_Finger02",
    "Index_Proximal_L"      : "ValveBiped.Bip01_L_Finger1",
    "Index_Intermediate_L"  : "ValveBiped.Bip01_L_Finger11",
    "Index_Distal_L"        : "ValveBiped.Bip01_L_Finger12",
    "Middle_Proximal_L"     : "ValveBiped.Bip01_L_Finger2",
    "Middle_Intermediate_L" : "ValveBiped.Bip01_L_Finger21",
    "Middle_Distal_L"       : "ValveBiped.Bip01_L_Finger22",
    "Ring_Proximal_L"       : "ValveBiped.Bip01_L_Finger3",
    "Ring_Intermediate_L"   : "ValveBiped.Bip01_L_Finger31",
    "Ring_Distal_L"         : "ValveBiped.Bip01_L_Finger32",
    "Little_Proximal_L"     : "ValveBiped.Bip01_L_Finger4",
    "Little_Intermediate_L" : "ValveBiped.Bip01_L_Finger41",
    "Little_Distal_L"       : "ValveBiped.Bip01_L_Finger42",
    
    # Fingers (Left) IV
    "Thumb1_l"              : "ValveBiped.Bip01_L_Finger0",
    "Thumb2_l"              : "ValveBiped.Bip01_L_Finger01",
    "Thumb3_l"              : "ValveBiped.Bip01_L_Finger02",
    "IndexFinger1_l"        : "ValveBiped.Bip01_L_Finger1",
    "IndexFinger2_l"        : "ValveBiped.Bip01_L_Finger11",
    "IndexFinger3_l"        : "ValveBiped.Bip01_L_Finger12",
    "MiddleFinger1_l"       : "ValveBiped.Bip01_L_Finger2",
    "MiddleFinger2_l"       : "ValveBiped.Bip01_L_Finger21",
    "MiddleFinger3_l"       : "ValveBiped.Bip01_L_Finger22",
    "RingFinger1_l"         : "ValveBiped.Bip01_L_Finger3",
    "RingFinger2_l"         : "ValveBiped.Bip01_L_Finger31",
    "RingFinger3_l"         : "ValveBiped.Bip01_L_Finger32",
    "LittleFinger1_l"       : "ValveBiped.Bip01_L_Finger4",
    "LittleFinger2_l"       : "ValveBiped.Bip01_L_Finger41",
    "LittleFinger3_l"       : "ValveBiped.Bip01_L_Finger42",

    # ---- Right ARM ----
    "Shoulder_R"            : "ValveBiped.Bip01_R_Clavicle",
    "Shoulder_r"            : "ValveBiped.Bip01_R_Clavicle",
    "Shoulder.R"            : "ValveBiped.Bip01_R_Clavicle",
    "Shoulder.r"            : "ValveBiped.Bip01_R_Clavicle",
    "Right_shoulder"        : "ValveBiped.Bip01_R_Clavicle",
    "Right shoulder"        : "ValveBiped.Bip01_R_Clavicle",
    "Right_Shoulder"        : "ValveBiped.Bip01_R_Clavicle",
    "Right Shoulder"        : "ValveBiped.Bip01_R_Clavicle",
    "right_shoulder"        : "ValveBiped.Bip01_R_Clavicle",
    "right shoulder"        : "ValveBiped.Bip01_R_Clavicle",
    "RightShoulder"         : "ValveBiped.Bip01_R_Clavicle",

    "UpperArm_R"            : "ValveBiped.Bip01_R_UpperArm",
    "UpperArm_r"            : "ValveBiped.Bip01_R_UpperArm",
    "Upper_arm.R"           : "ValveBiped.Bip01_R_UpperArm",
    "Upper_arm.r"           : "ValveBiped.Bip01_R_UpperArm",
    "Right_arm"             : "ValveBiped.Bip01_R_UpperArm",
    "Right arm"             : "ValveBiped.Bip01_R_UpperArm",
    "Right_Arm"             : "ValveBiped.Bip01_R_UpperArm",
    "Right Arm"             : "ValveBiped.Bip01_R_UpperArm",
    "RightUpperArm"         : "ValveBiped.Bip01_R_UpperArm",

    "LowerArm_R"            : "ValveBiped.Bip01_R_Forearm",
    "Lower_arm.R"           : "ValveBiped.Bip01_R_Forearm",
    "LowerArm_r"            : "ValveBiped.Bip01_R_Forearm",
    "Lower_arm.r"           : "ValveBiped.Bip01_R_Forearm",
    "Right_elbow"           : "ValveBiped.Bip01_R_Forearm",
    "Right elbow"           : "ValveBiped.Bip01_R_Forearm",
    "Right_Elbow"           : "ValveBiped.Bip01_R_Forearm",
    "Right Elbow"           : "ValveBiped.Bip01_R_Forearm",
    "RightLowerArm"         : "ValveBiped.Bip01_R_Forearm",

    "Hand_R"                : "ValveBiped.Bip01_R_Hand",
    "Hand.R"                : "ValveBiped.Bip01_R_Hand",
    "Hand_r"                : "ValveBiped.Bip01_R_Hand",
    "Hand.r"                : "ValveBiped.Bip01_R_Hand",
    "Right_wrist"           : "ValveBiped.Bip01_R_Hand",
    "Right wrist"           : "ValveBiped.Bip01_R_Hand",
    "Right_Wrist"           : "ValveBiped.Bip01_R_Hand",
    "Right Wrist"           : "ValveBiped.Bip01_R_Hand",
    "RightHand"             : "ValveBiped.Bip01_R_Hand", 

    # Fingers (Right) I
    "ThumbProximal_R"       : "ValveBiped.Bip01_R_Finger0",
    "ThumbIntermediate_R"   : "ValveBiped.Bip01_R_Finger01",
    "ThumbDistal_R"         : "ValveBiped.Bip01_R_Finger02",
    "IndexProximal_R"       : "ValveBiped.Bip01_R_Finger1",
    "IndexIntermediate_R"   : "ValveBiped.Bip01_R_Finger11",
    "IndexDistal_R"         : "ValveBiped.Bip01_R_Finger12",
    "MiddleProximal_R"      : "ValveBiped.Bip01_R_Finger2",
    "MiddleIntermediate_R"  : "ValveBiped.Bip01_R_Finger21",
    "MiddleDistal_R"        : "ValveBiped.Bip01_R_Finger22",
    "RingProximal_R"        : "ValveBiped.Bip01_R_Finger3",
    "RingIntermediate_R"    : "ValveBiped.Bip01_R_Finger31",
    "RingDistal_R"          : "ValveBiped.Bip01_R_Finger32",
    "LittleProximal_R"      : "ValveBiped.Bip01_R_Finger4",
    "LittleIntermediate_R"  : "ValveBiped.Bip01_R_Finger41",
    "LittleDistal_R"        : "ValveBiped.Bip01_R_Finger42",
    
    # Fingers (Right) II
    "Thumb01_r"             : "ValveBiped.Bip01_R_Finger0",
    "Thumb02_r"             : "ValveBiped.Bip01_R_Finger01",
    "Thumb03_r"             : "ValveBiped.Bip01_R_Finger02",
    "Index01_r"             : "ValveBiped.Bip01_R_Finger1",
    "Index02_r"             : "ValveBiped.Bip01_R_Finger11",
    "Index03_r"             : "ValveBiped.Bip01_R_Finger12",
    "Middle01_r"            : "ValveBiped.Bip01_R_Finger2",
    "Middle02_r"            : "ValveBiped.Bip01_R_Finger21",
    "Middle03_r"            : "ValveBiped.Bip01_R_Finger22",
    "Ring01_r"              : "ValveBiped.Bip01_R_Finger3",
    "Ring02_r"              : "ValveBiped.Bip01_R_Finger31",
    "Ring03_r"              : "ValveBiped.Bip01_R_Finger32",
    "Little01_r"            : "ValveBiped.Bip01_R_Finger4",
    "Little02_r"            : "ValveBiped.Bip01_R_Finger41",
    "Little03_r"            : "ValveBiped.Bip01_R_Finger42",
    
    # Fingers (Right) III
    "Thumb Proximal_R"      : "ValveBiped.Bip01_R_Finger0",
    "Thumb Intermediate_R"  : "ValveBiped.Bip01_R_Finger01",
    "Thumb Distal_R"        : "ValveBiped.Bip01_R_Finger02",
    "Index Proximal_R"      : "ValveBiped.Bip01_R_Finger1",
    "Index Intermediate_R"  : "ValveBiped.Bip01_R_Finger11",
    "Index Distal_R"        : "ValveBiped.Bip01_R_Finger12",
    "Middle Proximal_R"     : "ValveBiped.Bip01_R_Finger2",
    "Middle Intermediate_R" : "ValveBiped.Bip01_R_Finger21",
    "Middle Distal_R"       : "ValveBiped.Bip01_R_Finger22",
    "Ring Proximal_R"       : "ValveBiped.Bip01_R_Finger3",
    "Ring Intermediate_R"   : "ValveBiped.Bip01_R_Finger31",
    "Ring Distal_R"         : "ValveBiped.Bip01_R_Finger32",
    "Little Proximal_R"     : "ValveBiped.Bip01_R_Finger4",
    "Little Intermediate_R" : "ValveBiped.Bip01_R_Finger41",
    "Little Distal_R"       : "ValveBiped.Bip01_R_Finger42",
    
    # Fingers (Right) IV
    "Thumb Proximal.R"      : "ValveBiped.Bip01_R_Finger0",
    "Thumb Intermediate.R"  : "ValveBiped.Bip01_R_Finger01",
    "Thumb Distal.R"        : "ValveBiped.Bip01_R_Finger02",
    "Index Proximal.R"      : "ValveBiped.Bip01_R_Finger1",
    "Index Intermediate.R"  : "ValveBiped.Bip01_R_Finger11",
    "Index Distal.R"        : "ValveBiped.Bip01_R_Finger12",
    "Middle Proximal.R"     : "ValveBiped.Bip01_R_Finger2",
    "Middle Intermediate.R" : "ValveBiped.Bip01_R_Finger21",
    "Middle Distal.R"       : "ValveBiped.Bip01_R_Finger22",
    "Ring Proximal.R"       : "ValveBiped.Bip01_R_Finger3",
    "Ring Intermediate.R"   : "ValveBiped.Bip01_R_Finger31",
    "Ring Distal.R"         : "ValveBiped.Bip01_R_Finger32",
    "Little Proximal.R"     : "ValveBiped.Bip01_R_Finger4",
    "Little Intermediate.R" : "ValveBiped.Bip01_R_Finger41",
    "Little Distal.R"       : "ValveBiped.Bip01_R_Finger42",
    
    # Fingers (Right) V
    "Thumb_Proximal_R"      : "ValveBiped.Bip01_R_Finger0",
    "Thumb_Intermediate_R"  : "ValveBiped.Bip01_R_Finger01",
    "Thumb_Distal_R"        : "ValveBiped.Bip01_R_Finger02",
    "Index_Proximal_R"      : "ValveBiped.Bip01_R_Finger1",
    "Index_Intermediate_R"  : "ValveBiped.Bip01_R_Finger11",
    "Index_Distal_R"        : "ValveBiped.Bip01_R_Finger12",
    "Middle_Proximal_R"     : "ValveBiped.Bip01_R_Finger2",
    "Middle_Intermediate_R" : "ValveBiped.Bip01_R_Finger21",
    "Middle_Distal_R"       : "ValveBiped.Bip01_R_Finger22",
    "Ring_Proximal_R"       : "ValveBiped.Bip01_R_Finger3",
    "Ring_Intermediate_R"   : "ValveBiped.Bip01_R_Finger31",
    "Ring_Distal_R"         : "ValveBiped.Bip01_R_Finger32",
    "Little_Proximal_R"     : "ValveBiped.Bip01_R_Finger4",
    "Little_Intermediate_R" : "ValveBiped.Bip01_R_Finger41",
    "Little_Distal_R"       : "ValveBiped.Bip01_R_Finger42",
    
    # Fingers (Right) IV
    "Thumb1_r"              : "ValveBiped.Bip01_R_Finger0",
    "Thumb2_r"              : "ValveBiped.Bip01_R_Finger01",
    "Thumb3_r"              : "ValveBiped.Bip01_R_Finger02",
    "IndexFinger1_r"        : "ValveBiped.Bip01_R_Finger1",
    "IndexFinger2_r"        : "ValveBiped.Bip01_R_Finger11",
    "IndexFinger3_r"        : "ValveBiped.Bip01_R_Finger12",
    "MiddleFinger1_r"       : "ValveBiped.Bip01_R_Finger2",
    "MiddleFinger2_r"       : "ValveBiped.Bip01_R_Finger21",
    "MiddleFinger3_r"       : "ValveBiped.Bip01_R_Finger22",
    "RingFinger1_r"         : "ValveBiped.Bip01_R_Finger3",
    "RingFinger2_r"         : "ValveBiped.Bip01_R_Finger31",
    "RingFinger3_r"         : "ValveBiped.Bip01_R_Finger32",
    "LittleFinger1_r"       : "ValveBiped.Bip01_R_Finger4",
    "LittleFinger2_r"       : "ValveBiped.Bip01_R_Finger41",
    "LittleFinger3_r"       : "ValveBiped.Bip01_R_Finger42",
    
    # ---- LEFT LEG ----
    "UpperLeg_L"            : "ValveBiped.Bip01_L_Thigh",
    "Upper_leg.L"           : "ValveBiped.Bip01_L_Thigh",
    "Upperleg_L"            : "ValveBiped.Bip01_L_Thigh",
    "Upper_Leg.L"           : "ValveBiped.Bip01_L_Thigh",
    "Left_leg"              : "ValveBiped.Bip01_L_Thigh",
    "Left leg"              : "ValveBiped.Bip01_L_Thigh",
    "Left_Leg"              : "ValveBiped.Bip01_L_Thigh",
    "Left Leg"              : "ValveBiped.Bip01_L_Thigh",

    "LowerLeg_L"            : "ValveBiped.Bip01_L_Calf",
    "Lower_leg.L"           : "ValveBiped.Bip01_L_Calf",
    "Lowerleg_L"            : "ValveBiped.Bip01_L_Calf",
    "Lower_Leg.L"           : "ValveBiped.Bip01_L_Calf",
    "Left_knee"             : "ValveBiped.Bip01_L_Calf",
    "Left knee"             : "ValveBiped.Bip01_L_Calf",
    "Left_Knee"             : "ValveBiped.Bip01_L_Calf",
    "Left Knee"             : "ValveBiped.Bip01_L_Calf",

    "Foot_L"                : "ValveBiped.Bip01_L_Foot",
    "Foot.L"                : "ValveBiped.Bip01_L_Foot",
    "Left_ankle"            : "ValveBiped.Bip01_L_Foot",
    "Left ankle"            : "ValveBiped.Bip01_L_Foot",  
    "Left foot"             : "ValveBiped.Bip01_L_Foot",  
    "Left_foot"             : "ValveBiped.Bip01_L_Foot",  
    "Left_Ankle"            : "ValveBiped.Bip01_L_Foot",
    "Left Ankle"            : "ValveBiped.Bip01_L_Foot",  
    "Left Foot"             : "ValveBiped.Bip01_L_Foot",  
    "Left_Foot"             : "ValveBiped.Bip01_L_Foot",  
    

    "Toe_L"                 : "ValveBiped.Bip01_L_Toe0",
    "Toe.L"                 : "ValveBiped.Bip01_L_Toe0",
    "Toe_l"                 : "ValveBiped.Bip01_L_Toe0",
    "Toe.l"                 : "ValveBiped.Bip01_L_Toe0",
    "toe_l"                 : "ValveBiped.Bip01_L_Toe0",
    "toe.l"                 : "ValveBiped.Bip01_L_Toe0",
    "Left_Toe"              : "ValveBiped.Bip01_L_Toe0",
    "Left toe"              : "ValveBiped.Bip01_L_Toe0",
    "Foot.L.001"            : "ValveBiped.Bip01_L_Toe0",

    # ---- RIGHT LEG ----
    "UpperLeg_R"            : "ValveBiped.Bip01_R_Thigh",
    "Upper_leg.R"           : "ValveBiped.Bip01_R_Thigh",
    "Upperleg_R"            : "ValveBiped.Bip01_R_Thigh",
    "Upper_Leg.R"           : "ValveBiped.Bip01_R_Thigh",
    "Right_leg"             : "ValveBiped.Bip01_R_Thigh",
    "Right leg"             : "ValveBiped.Bip01_R_Thigh",
    "Right_Leg"             : "ValveBiped.Bip01_R_Thigh",
    "Right Leg"             : "ValveBiped.Bip01_R_Thigh",

    "LowerLeg_R"            : "ValveBiped.Bip01_R_Calf",
    "Lower_leg.R"           : "ValveBiped.Bip01_R_Calf",
    "Lowerleg_R"            : "ValveBiped.Bip01_R_Calf",
    "Lower_Leg.R"           : "ValveBiped.Bip01_R_Calf",
    "Right_knee"            : "ValveBiped.Bip01_R_Calf",
    "Right knee"            : "ValveBiped.Bip01_R_Calf",
    "Right_Knee"            : "ValveBiped.Bip01_R_Calf",
    "Right Knee"            : "ValveBiped.Bip01_R_Calf",

    "Foot_R"                : "ValveBiped.Bip01_R_Foot",
    "Foot.R"                : "ValveBiped.Bip01_R_Foot",
    "Right_ankle"           : "ValveBiped.Bip01_R_Foot",
    "Right ankle"           : "ValveBiped.Bip01_R_Foot",  
    "Right foot"            : "ValveBiped.Bip01_R_Foot",  
    "Right_foot"            : "ValveBiped.Bip01_R_Foot",  
    "Right_Ankle"           : "ValveBiped.Bip01_R_Foot",
    "Right Ankle"           : "ValveBiped.Bip01_R_Foot",  
    "Right Foot"            : "ValveBiped.Bip01_R_Foot",  
    "Right_Foot"            : "ValveBiped.Bip01_R_Foot",  
    

    "Toe_R"                 : "ValveBiped.Bip01_R_Toe0",
    "Toe.R"                 : "ValveBiped.Bip01_R_Toe0",
    "Toe_r"                 : "ValveBiped.Bip01_R_Toe0",
    "Toe.r"                 : "ValveBiped.Bip01_R_Toe0",
    "toe_r"                 : "ValveBiped.Bip01_R_Toe0",
    "toe.r"                 : "ValveBiped.Bip01_R_Toe0",
    "Right_Toe"             : "ValveBiped.Bip01_R_Toe0",
    "Right toe"             : "ValveBiped.Bip01_R_Toe0",
    "Foot.R.001"            : "ValveBiped.Bip01_R_Toe0",
}

# ===============================
# 1) Cleanup underscores to avoid making them corrective
# ===============================
for mesh in bpy.data.meshes:
    if mesh.shape_keys:
        for sk in mesh.shape_keys.key_blocks:
            sk.name = sk.name.replace('_', '')

# ===============================
# 2) Rename bones
# ===============================
for arm in bpy.data.armatures:
    for bone in arm.bones:
        if bone.name in bone_replacements:
            bone.name = bone_replacements[bone.name]

print("✅ Bones renamed to Valvebiped bones successfully!")
